---
- hosts: all
  force_handlers: yes
  vars:
   docker_version: "{{ dversion }}" 
   docker_compose_version: "{{ dcversion }}"
  tasks:
   - name: Install docker to CentOS
     block:
       - name: Remove old versions
         yum:
           name:
             - docker
             - docker-client
             - docker-client-latest
             - docker-common
             - docker-latest-logrotate
             - docker-logrotate
             - docker-engine
           state: absent

       - name: Install yum-config-manager
         yum:
            name: yum-utils
            state: present

       - name: Add docker repo by yum config manager
         shell:
           cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

       - name: install containerd.io
         dnf:
           name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm'
           state: present

       - name: Install Docker
         yum:
            name:
             - docker-ce-{{ docker_version }}
             - docker-ce-cli-{{ docker_version }}
             - containerd.io
            state: present
            enablerepo: "docker-ce"
            update_cache: yes 

     when: ansible_facts['distribution'] == 'CentOS'
   
   - name: Install docker to Mint
     block:
       - name: Remove old versions
         apt:
            name:
              - docker
              - docker-engine
              - docker.io
              - containerd
              - runc
            state: absent

       - name: Prerquisites installation
         apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg-agent
              - software-properties-common
            state: present

       - name: Add GPG key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
         become: true

       - name: Create file docker.list
         file: 
            path: /etc/apt/sources.list.d/docker.list
            state: touch
         become: true 
             
       - name: add Repo
         shell:
            cmd: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
         become: true

       - name: install docker
         apt:
            name:
              - docker-ce=5:{{ docker_version }}~3-0~ubuntu-bionic
              - docker-ce-cli=5:{{ docker_version }}~3-0~ubuntu-bionic
              - containerd.io
            state: present
            update_cache: yes
         become: true

     when: ansible_facts['distribution'] == 'Linux Mint'

   - name: Install docker-compose
     get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        force: yes
     become: true

   - name: +x permition to docker_compose
     file: 
        dest: /usr/local/bin/docker-compose 
        mode: a+x
